<?php

namespace CiviCoop\VragenboomBundle\Entity;

use Doctrine\ORM\EntityRepository;
use CiviCoop\VragenboomBundle\Entity\Type;

/**
 * ActieDefinitieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActieDefinitieRepository extends EntityRepository
{
}
