<?php

namespace CiviCoop\VragenboomBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AdviesRapportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdviesRapportRepository extends EntityRepository
{
	public function findAllActive()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p FROM CiviCoopVragenboomBundle:AdviesRapport p WHERE p.closed = false ORDER BY p.date ASC'
            )
            ->getResult();
    }
	
	public function findOneByCaseIdAndActivityId($caseId, $activityId) {
		$query = $this->getEntityManager()
        ->createQuery(
            'SELECT p FROM CiviCoopVragenboomBundle:AdviesRapport p WHERE p.caseId = :caseId AND p.activityId = :activityId ORDER BY p.date ASC'
        )
		->setParameter(':caseId', $caseId)
		->setParameter(':activityId', $activityId);
		
		try {
			return $query->getSingleResult();
		} catch (\Doctrine\ORM\NoResultException $e) {
			return null;
		}
		
	}
	
	public function findOneById($id) {
		$query = $this->getEntityManager()
        ->createQuery(
            'SELECT r, regel, actie, object, ruimte FROM CiviCoopVragenboomBundle:AdviesRapport r LEFT JOIN r.regels regel LEFT JOIN regel.actie actie LEFT JOIN actie.object object LEFT JOIN object.ruimte ruimte WHERE r.id = :id ORDER BY ruimte.naam, object.naam, actie.actie'
        )
		->setParameter(':id', $id);
		
		try {
			return $query->getSingleResult();
		} catch (\Doctrine\ORM\NoResultException $e) {
			return null;
		}
	}
}
