<?php

namespace CiviCoop\VragenboomBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EindRapportRegelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EindRapportRegelRepository extends EntityRepository
{
}
