<?php

namespace CiviCoop\VragenboomBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RuimteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RuimteRepository extends EntityRepository {

  public function findAllOrderByNaam() {
    return $this->getEntityManager()
            ->createQuery(
                'SELECT p FROM CiviCoopVragenboomBundle:Ruimte p ORDER BY p.naam ASC'
            )
            ->getResult();
  }

}
