security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        CiviCoop\InsiteAuthenticatorBundle\Security\User\InsiteUser: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
#                    jaap: { password: jaap1234, roles: [ 'ROLE_ADMIN' ] }
        insite:
            id: insite.security.authentication.userprovider	

    firewalls:
        vragenboom_login:
            pattern:  ^/login$
            anonymous: true			
            security: false
        assets:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
            anonymous: true
        vragenboom:
            pattern: ^/
#            provider: insite
            form_login:
                check_path: civicoop_vragenboom_login_check
                login_path: civicoop_vragenboom_login
                always_use_default_target_path: true
                default_target_path: /adviesrapport
            logout:
                path:   civicoop_vragenboom_logout
                target: /
                invalidate_session: false
            remember_me:
                key:      "%secret%"
                lifetime: 31536000 # 365 days in seconds
                path:     /
                domain:   ~ # Defaults to the current domain from $_SERVER
#            anonymous:    true
            insite: ~

    access_control:
        - { path: ^/, roles: IS_AUTHENTICATED_REMEMBERED }      
