civicoop_vragenboom_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: CiviCoopVragenboomBundle:Default:index }
civicoop_vragenboom_login_check:
    pattern:  /login_check
    defaults: { _controller: CiviCoopVragenboomBundle:Default:securityCheck }
civicoop_vragenboom_login:
    pattern:  /login
    defaults: { _controller: CiviCoopVragenboomBundle:Default:login }
civicoop_vragenboom_logout:
    pattern:  /logout
    defaults: { _controller: CiviCoopVragenboomBundle:Default:logout }

adviesrapport:
    resource: "@CiviCoopVragenboomBundle/Controller/AdviesRapportController.php"
    type:     annotation
adviesrapportregel:
    resource: "@CiviCoopVragenboomBundle/Controller/AdviesRapportRegelController.php"
    type:     annotation	
ruimtes:
    resource: "@CiviCoopVragenboomBundle/Controller/RuimteController.php"
    type:     annotation
objects:
    resource: "@CiviCoopVragenboomBundle/Controller/ObjectController.php"
    type:     annotation
actiedefinities:
    resource: "@CiviCoopVragenboomBundle/Controller/ActieDefinitieController.php"
    type:     annotation
