parameters:
#    civicoop.dgw.mutatieproces.case_type: DossierOpzeggingHuurcontract
    civicoop.dgw.mutatieproces.case_type: Huuropzeggingsdossier    
    civicoop.dgw.mutatieproces.activity_type_adviesgesprek: Adviesgesprek
    civicoop.dgw.mutatieproces.activity_type_eindgesprek: Eindgesprek
#    civicoop.dgw.mutatieproces.eindehuurcontract: einde_huurcontract
    civicoop.dgw.mutatieproces.eindehuurcontract: vge
    civicoop.dgw.mutatieproces.huuropzegging: huur_opzegging
    civicoop.dgw.mutatieproces.rapport_factory_class: CiviCoop\VragenboomBundle\Service\RapportFactory

services:
    civicoop.dgw.mutatieproces.civicase:
        class: CiviCoop\VragenboomBundle\Service\CiviCase
        arguments: 
            entityManager: @doctrine.orm.entity_manager
            api: @civicoop.civicrm.api 
            factory: @civicoop.vragenboom.rapportfactory
            casetype: %civicoop.dgw.mutatieproces.case_type%
            activitytype_adviesgesprek: %civicoop.dgw.mutatieproces.activity_type_adviesgesprek%
            activitytype_eindgesprek: %civicoop.dgw.mutatieproces.activity_type_eindgesprek%
            eindehuurcontract: %civicoop.dgw.mutatieproces.eindehuurcontract%
            huuropzegging: %civicoop.dgw.mutatieproces.huuropzegging%
    civicoop.vragenboom.rapportfactory:
        class: %civicoop.dgw.mutatieproces.rapport_factory_class%
        arguments:
            entityManager: @doctrine.orm.entity_manager
            translator: @translator