parameters:
    civicoop.dgw.mutatieproces.rapport_factory_class: CiviCoop\VragenboomBundle\Service\RapportFactory

services:
    civicoop.dgw.mutatieproces.civicontact:
        class: CiviCoop\VragenboomBundle\Service\CiviContact
        arguments: 
            entityManager: @doctrine.orm.entity_manager
            api: @civicoop.civicrm.api 
            factory: @civicoop.vragenboom.rapportfactory
    civicoop.dgw.mutatieproces.civicase:
        class: CiviCoop\VragenboomBundle\Service\CiviCase
        arguments: 
            entityManager: @doctrine.orm.entity_manager
            api: @civicoop.civicrm.api 
            factory: @civicoop.vragenboom.rapportfactory
    civicoop.vragenboom.rapportfactory:
        class: %civicoop.dgw.mutatieproces.rapport_factory_class%
        arguments:
            entityManager: @doctrine.orm.entity_manager
            translator: @translator