parameters:
    insite_user_provider.class: CiviCoop\InsiteAuthenticatorBundle\Security\User\InsiteUserProvider

services:
    insite.security.authentication.provider:
        class:  CiviCoop\InsiteAuthenticatorBundle\Security\Authentication\Provider\InsiteProvider
        arguments: ["@civi_coop_json_rest.http", "%civicoop.insiteauthenticator.url%", "%civicoop.insiteauthenticator.hostname%", "@civicoop.civicrm.api", "@logger"]
    insite.security.authentication.listener:
        class:  CiviCoop\InsiteAuthenticatorBundle\Security\Firewall\InsiteListener
        arguments: ["@security.context", "@security.authentication.manager"]
    insite.security.authentication.userprovider:
        class: "%insite_user_provider.class%"